[package]
name = "qdral-provider-network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
qdral-contracts = { path = "../qdral-contracts" }
serde_json.workspace = true
sha2.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_Foundation", "Win32_Networking_WinHttp", "Win32_Networking_WinSock"] }
